version: '3.4'

services:
  servicea:
    image: ${DOCKER_REGISTRY-}servicea
    build:
      context: .
      dockerfile: ServiceA/Dockerfile
    ports:
      - 23300:443
      - 23301:80

  serviceb:
    image: ${DOCKER_REGISTRY-}serviceb
    build:
      context: .
      dockerfile: ServiceB/Dockerfile
    ports:
      - 23302:443
      - 23303:80

  dynamicconfiguration.ui:
    image: ${DOCKER_REGISTRY-}dynamicconfigurationui
    build:
      context: .
      dockerfile: DynamicConfiguration.UI/Dockerfile
    ports:
      - 23304:443
      - 23305:80